name: Deploy Tech Pulse Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          NEXT_PUBLIC_API_SERVER: ${{ vars.NEXT_PUBLIC_API_SERVER }}
          NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_SITEMAP_SECRET: ${{ vars.NEXT_PUBLIC_SITEMAP_SECRET }}
          NEXT_PUBLIC_YANDEX_VERIFICATION: ${{ vars.NEXT_PUBLIC_YANDEX_VERIFICATION }}
          NEXT_PUBLIC_GOOGLE_VERIFICATION: ${{ vars.NEXT_PUBLIC_GOOGLE_VERIFICATION }}
          NEXT_PUBLIC_YANDEX_METRIKA_ID: ${{ vars.NEXT_PUBLIC_YANDEX_METRIKA_ID }}
          NEXT_PUBLIC_GOOGLE_TAG: ${{ vars.NEXT_PUBLIC_GOOGLE_TAG }}
          NEXT_PUBLIC_YANDEX_BLOCK_ID1: ${{ vars.NEXT_PUBLIC_YANDEX_BLOCK_ID1 }}
          NEXT_PUBLIC_YANDEX_BLOCK_ID2: ${{ vars.NEXT_PUBLIC_YANDEX_BLOCK_ID2 }}
          NEXT_PUBLIC_YANDEX_BLOCK_ID3: ${{ vars.NEXT_PUBLIC_YANDEX_BLOCK_ID3 }}
          NEXT_PUBLIC_UPTOLIKE_WIDGET_PID: ${{ vars.NEXT_PUBLIC_UPTOLIKE_WIDGET_PID }}
        run: npm run build

      - name: Stop Apache on VDS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VDS_SSH_KEY }}
          SERVER_HOST: ${{ secrets.VDS_HOST }}
          SERVER_USER: ${{ secrets.VDS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "sudo systemctl stop apache2"

      - name: Deploy to VDS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VDS_SSH_KEY }}
          SERVER_HOST: ${{ secrets.VDS_HOST }}
          SERVER_USER: ${{ secrets.VDS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p /var/www/techpulseclient"
          rsync -avz --exclude='.git' --exclude='node_modules' --exclude='.github' . $SERVER_USER@$SERVER_HOST:/var/www/techpulseclient
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd /var/www/techpulseclient && npm install && pm2 restart techpulseclient"

      - name: Start Apache on VDS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VDS_SSH_KEY }}
          SERVER_HOST: ${{ secrets.VDS_HOST }}
          SERVER_USER: ${{ secrets.VDS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "sudo systemctl start apache2"
