name: Deploy Tech Pulse Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        run: |
          source ~/.nvm/nvm.sh
          nvm use v18.20.4
          node -v

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to VDS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VDS_SSH_KEY }}
          SERVER_HOST: ${{ secrets.VDS_HOST }}
          SERVER_USER: ${{ secrets.VDS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p /var/www/techpulseclient"
          rsync -avz --exclude='.git' --exclude='node_modules' --exclude='.github' . $SERVER_USER@$SERVER_HOST:/var/www/techpulseclient
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd /var/www/techpulseclient && npm install && npm run start"
